name: New Variable
description: Here you can suggest a new variable to be added to the PRIO-GRID meta-data.
title: "[New Variable]: "
labels: ["feature"]
assignees:
  - kvelleby  
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new variable for PRIO-GRID!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: variable_name
    attributes:
      label: Variable name
      description: Your suggested name for the variable
      placeholder: ex. capital_conflict
    validations:
      required: false
  - type: textarea
    id: variable_idea
    attributes:
      label: Explain your idea
      description: Include the full name of sources required to calculate the variable and how you would calculate it.
      placeholder: "ex. Using caplong and caplat from ETH ICR cShapes and best from UCDP GED, calculate the capital distance-weigthed battle-related deaths in each cell."
    validations:
      required: true   

