# Helper operator for NULL coalescing
`%||%` <- function(x, y) if (is.null(x)) y else x

#' Get spatial configuration hash
#'
#' Creates a 6-character MD5 hash of the current spatial options from config.
#'
#' @return Character string with 6-character hash
#' @keywords internal
get_spatial_hash <- function(config = pg_current_config()) {
  spatial_options <- list(
    nrow = config$nrow,
    ncol = config$ncol,
    crs = config$crs,
    extent = as.vector(config$extent)
  )

  hash_input <- paste(spatial_options, collapse = "_")
  digest::digest(hash_input, algo = "md5") |> substr(1, 6)
}

#' Get temporal configuration hash
#'
#' Creates a 6-character MD5 hash of the current temporal options from config.
#' Rounds end_date to avoid creating new hashes for small date changes.
#'
#' @return Character string with 6-character hash
#' @keywords internal
get_temporal_hash <- function(config = pg_current_config()) {
  rounded_end_date <- lubridate::floor_date(
    config$end_date,
    config$temporal_resolution
  )

  temporal_options <- list(
    temporal_resolution = config$temporal_resolution,
    start_date = config$start_date,
    end_date = rounded_end_date
  )

  hash_input <- paste(temporal_options, collapse = "_")
  digest::digest(hash_input, algo = "md5") |> substr(1, 6)
}


#' Path to store PRIOGRID results
#'
#' Returns the file path where PRIOGRID data is stored. The path structure depends
#' on whether you're working with custom data or official releases.
#'
#' @param version Character string specifying PRIOGRID version. Use for official releases.
#' @param type Character string specifying release type (e.g., "05deg_yearly"). Use for official releases.
#' @param spatial_hash Character string with 6-character spatial hash. If NULL, computed from current config.
#' @param temporal_hash Character string with 6-character temporal hash. If NULL, computed from current config.
#' @param config A `pg_config` object. Defaults to [pg_current_config()].
#'
#' @return Character string with file path
#' @export
#'
#' @examples
#' \dontrun{
#'   # Custom data with current config
#'   pgout_path()
#'
#'   # Custom data with specific hashes
#'   pgout_path(spatial_hash = "a3f2e1", temporal_hash = "9c8b7a")
#'
#'   # Official release
#'   pgout_path(version = "3.0.1", type = "05deg_yearly")
#' }
pgout_path <- function(version = NULL,
                       type = NULL,
                       spatial_hash = NULL,
                       temporal_hash = NULL,
                       config = pg_current_config()) {
  base_path <- file.path(pg_rawfolder(), "priogrid")

  if (!is.null(type)) {
    # Release mode
    if (is.null(version)) {
      stop("Release mode requires both 'version' and 'type' parameters")
    }
    return(file.path(base_path, "releases", version, type))
  }

  # Custom mode
  pkg_version <- version %||% packageVersion("priogrid")
  s_hash <- spatial_hash %||% get_spatial_hash(config)
  t_hash <- temporal_hash %||% get_temporal_hash(config)

  file.path(base_path, "custom", pkg_version, s_hash, t_hash)
}


#' Calculate PRIO-GRID variables
#'
#' Calculates PRIO-GRID variables based on current config and saves them
#' to disk. Each variable is computed by calling its corresponding gen_*() function
#' and saved as a Cloud-Optimized GeoTIFF (COG) under the \code{cog/} sub-directory.
#'
#' @param varnames Character vector with variable names from [pgvariables].
#'   If NULL (default), calculates all available variables.
#' @param overwrite Logical. If FALSE (default), skips variables that already
#'   exist in the output folder. If TRUE, recalculates all specified variables.
#' @param config A `pg_config` object. Defaults to [pg_current_config()].
#'
#' @return NULL (invisibly). Called for side effects (saving files).
#' @export
#'
#' @examples
#' \dontrun{
#'   # Calculate single variable
#'   calc_pg("ne_disputed_area_share")
#'   r <- load_pgvariable("ne_disputed_area_share")
#'
#'   # Calculate all variables
#'   calc_pg()
#'
#'   # Recalculate existing variables
#'   calc_pg(overwrite = TRUE)
#' }
calc_pg <- function(varnames = NULL, overwrite = FALSE, config = pg_current_config()) {
  if (is.null(varnames)) {
    varnames <- pgvariables$name
  }

  valid_varnames <- varnames[varnames %in% pgvariables$name]
  invalid_varnames <- varnames[!varnames %in% pgvariables$name]
  if (length(invalid_varnames) > 0) {
    message(paste("Ignored varnames:", paste(invalid_varnames, collapse = ", ")))
  }

  if (length(valid_varnames) == 0) {
    stop("No valid varnames supplied. Use names in `pgvariables`")
  }

  s_hash <- get_spatial_hash(config)
  t_hash <- get_temporal_hash(config)
  save_to <- pgout_path(spatial_hash = s_hash, temporal_hash = t_hash)

  if (!dir.exists(save_to)) {
    dir.create(save_to, recursive = TRUE)
  }

  # Write config record on first creation
  config_file <- file.path(save_to, "_config.R")
  if (!file.exists(config_file)) {
    writeLines(c(
      paste0("# Generated by priogrid on ", Sys.Date()),
      paste0("# Spatial hash: ", s_hash, "  Temporal hash: ", t_hash),
      "cfg <- pg_config(",
      paste0("  nrow = ", config$nrow, "L,"),
      paste0("  ncol = ", config$ncol, "L,"),
      paste0("  crs = \"", config$crs, "\","),
      paste0("  extent = c(xmin = ", config$extent["xmin"],
             ", xmax = ", config$extent["xmax"],
             ", ymin = ", config$extent["ymin"],
             ", ymax = ", config$extent["ymax"], "),"),
      paste0("  temporal_resolution = \"", config$temporal_resolution, "\","),
      paste0("  start_date = as.Date(\"", config$start_date, "\"),"),
      paste0("  end_date = as.Date(\"", config$end_date, "\"),"),
      paste0("  verbose = ", config$verbose, ","),
      paste0("  automatic_download = ", config$automatic_download),
      ")"
    ), config_file)
  }

  existing_files <- list.files(file.path(save_to, "cog"), pattern = "\\.tif$") |>
    tools::file_path_sans_ext()

  if (!overwrite) {
    valid_varnames <- valid_varnames[!valid_varnames %in% existing_files]
  }

  if (length(valid_varnames) == 0) {
    message("All requested variables already exist. Use overwrite=TRUE to recalculate.")
    return(invisible(NULL))
  }

  # Calculate variables
  message(paste("Variables to calculate:", paste(valid_varnames, collapse = ", ")))
  message(paste("Saving to:", save_to))
  failed_vars <- character(0)
  for (varname in valid_varnames) {
    message(paste("Calculating", varname))
    result <- tryCatch({
      gen_fun <- get(paste0("gen_", varname))
      r <- gen_fun(config = config)
      save_pgvariable(r, varname, save_to = save_to)
      NULL
    }, error = function(e) {
      is_file_error <- grepl(
        "not found|does not exist|No such file|cannot open|missing files|No files in metadata",
        conditionMessage(e), ignore.case = TRUE
      )
      if (is_file_error) {
        warning(
          sprintf("Skipping '%s': a required source file is missing or unreadable.\n", varname),
          "  Error: ", conditionMessage(e), "\n",
          "  Check availability: pg_data_availability()\n",
          "  Download missing:   download_pg_rawdata()",
          call. = FALSE)
      } else {
        warning(
          sprintf("Skipping '%s': computation failed.\n", varname),
          "  Error: ", conditionMessage(e),
          call. = FALSE)
      }
      varname
    })
    if (!is.null(result)) failed_vars <- c(failed_vars, result)
  }

  if (length(failed_vars) > 0) {
    message(
      "calc_pg() completed with ", length(failed_vars), " failure(s): ",
      paste(failed_vars, collapse = ", "), "\n",
      "Succeeded: ", length(valid_varnames) - length(failed_vars),
      " / ", length(valid_varnames))
  }

  invisible(NULL)
}

# Internal: data-driven display stats from a built raster.
# value_min/value_max: overall min/max across layers (NA-robust).
# value_mean/value_std: per-layer mean/sd averaged across layers (display hint).
# nunique/class_values: distinct non-NA values, only for plot_type == "discrete".
# @keywords internal
.pg_variable_stats <- function(rast, plot_type = NA_character_) {
  empty <- list(value_min = NA_real_, value_max = NA_real_,
                value_mean = NA_real_, value_std = NA_real_,
                nunique = NA_integer_, class_values = NA_character_)
  if (terra::nlyr(rast) == 0L || terra::ncell(rast) == 0L) return(empty)

  g   <- terra::global(rast, fun = c("min", "max", "mean", "sd"), na.rm = TRUE)
  fin <- function(x) if (length(x) && is.finite(x)) x else NA_real_
  vmin  <- fin(suppressWarnings(min(g$min,   na.rm = TRUE)))
  vmax  <- fin(suppressWarnings(max(g$max,   na.rm = TRUE)))
  vmean <- fin(suppressWarnings(mean(g$mean, na.rm = TRUE)))
  vstd  <- fin(suppressWarnings(mean(g$sd,   na.rm = TRUE)))

  nuniq <- NA_integer_; cls <- NA_character_
  if (!is.na(plot_type) && plot_type == "discrete") {
    f <- terra::freq(rast, bylayer = FALSE)
    if (nrow(f) > 0L) {
      vals  <- sort(unique(f$value))
      nuniq <- length(vals)
      cls   <- paste(vals, collapse = ",")
    }
  }
  list(value_min = vmin, value_max = vmax, value_mean = vmean,
       value_std = vstd, nunique = nuniq, class_values = cls)
}

# Internal: recommended rio-tiler/matplotlib colormap for a plot_type.
# @keywords internal
.pg_colormap <- function(plot_type) {
  switch(as.character(plot_type),
    continuous    = "rdbu_r",   # diverging (temperature, elevation, SPEI)
    positive_real = "viridis",  # sequential magnitude
    count         = "inferno",  # sequential hotspot
    share         = "viridis",  # sequential 0-1
    discrete      = "tab20",    # qualitative
    "viridis")                  # default
}

# Internal: build the named pg_* GDAL metatag vector for a variable.
# Drop NA/empty fields so callers can assign terra::metags(r) <- ... directly.
# Accepts optional computed stats from .pg_variable_stats(); pg_colormap is
# derived from plot_type, never stored in pgvariables.
# @keywords internal
.pg_build_metatags <- function(varname, stats = NULL) {
  meta <- pgvariables[pgvariables$name == varname, ]
  if (nrow(meta) == 0L) stop("varname '", varname, "' not found in pgvariables.")

  cmap <- if (!is.na(meta$plot_type) && nzchar(meta$plot_type)) .pg_colormap(meta$plot_type) else NULL
  st   <- function(k) if (!is.null(stats) && !is.na(stats[[k]])) stats[[k]] else NULL

  c(
    pg_name      = meta$name,
    pg_static    = as.character(meta$static),
    if (!is.na(meta$label)     && nzchar(meta$label))     c(pg_label     = meta$label)     else NULL,
    if (!is.na(meta$unit)      && nzchar(meta$unit))      c(pg_unit      = meta$unit)      else NULL,
    if (!is.na(meta$transform) && nzchar(meta$transform)) c(pg_transform = meta$transform) else NULL,
    if (!is.na(meta$plot_type) && nzchar(meta$plot_type)) c(pg_plot_type = meta$plot_type) else NULL,
    if (!is.null(cmap))               c(pg_colormap     = cmap)                           else NULL,
    if (!is.null(st("value_min")))    c(pg_value_min    = as.character(stats$value_min))  else NULL,
    if (!is.null(st("value_max")))    c(pg_value_max    = as.character(stats$value_max))  else NULL,
    if (!is.null(st("value_mean")))   c(pg_value_mean   = as.character(stats$value_mean)) else NULL,
    if (!is.null(st("value_std")))    c(pg_value_std    = as.character(stats$value_std))  else NULL,
    if (!is.null(st("nunique")))      c(pg_nunique      = as.character(stats$nunique))    else NULL,
    if (!is.null(st("class_values"))) c(pg_class_values = stats$class_values)             else NULL
  )
}

#' Save a PRIO-GRID variable
#'
#' Saves a terra SpatRaster as a Cloud-Optimized GeoTIFF (COG) under the
#' \code{cog/} sub-directory of the dataset root. The variable must be listed
#' in [pgvariables]. Layer names, \code{time()}, and \code{units()} are
#' preserved natively inside the \code{.tif}. Plot metadata from [pgvariables]
#' (\code{label}, \code{unit}, \code{transform}, \code{plot_type}) is stamped as
#' \code{pg_*} GDAL metatags so the COG is self-describing. In addition,
#' \code{pg_colormap} (derived from \code{plot_type}), \code{pg_value_min},
#' \code{pg_value_max}, \code{pg_value_mean}, \code{pg_value_std} (computed
#' from the raster at save time), and — for discrete variables —
#' \code{pg_nunique} and \code{pg_class_values} are also stamped.
#' \code{value_*}, \code{nunique}, and \code{class_values} are computed from
#' the raster at save time; \code{colormap} is derived from \code{plot_type}.
#' These map directly onto rio-tiler/TiTiler \code{rescale} and
#' \code{colormap_name}.
#'
#' @param rast Terra SpatRaster object from a gen_*() function.
#' @param varname Character string with the variable name (must exist in pgvariables).
#' @param save_to Character string with the dataset root path. Defaults to current
#'   custom data location based on config.
#'
#' @return NULL (invisibly). Called for side effects (saving file).
#' @export
#'
#' @examples
#' \dontrun{
#'   r <- gen_ne_disputed_area_share()
#'   save_pgvariable(r, "ne_disputed_area_share")
#' }
save_pgvariable <- function(rast, varname, save_to = pgout_path()) {
  rlang::check_installed("terra", reason = "to save PRIO-GRID variable rasters")
  if (!varname %in% pgvariables$name) {
    stop("varname '", varname, "' not found in pgvariables.")
  }

  if (!dir.exists(save_to)) {
    stop("Output directory does not exist: ", save_to)
  }

  cog_dir <- file.path(save_to, "cog")
  if (!dir.exists(cog_dir)) dir.create(cog_dir, recursive = TRUE)

  filepath <- file.path(cog_dir, paste0(varname, ".tif"))

  meta <- pgvariables[pgvariables$name == varname, ]

  # Stamp time() for time-varying rasters whose layer names are ISO dates
  if (!isTRUE(meta$static) && all(is.na(terra::time(rast)))) {
    parsed <- tryCatch(as.Date(names(rast)), error = function(e) NULL)
    if (!is.null(parsed) && !any(is.na(parsed)))
      terra::time(rast) <- parsed
  }

  # Stamp units from pgvariables
  if (!is.na(meta$unit) && nzchar(meta$unit))
    terra::units(rast) <- meta$unit

  stats <- .pg_variable_stats(rast, plot_type = meta$plot_type)
  terra::metags(rast) <- .pg_build_metatags(varname, stats = stats)

  terra::writeRaster(rast, filepath, filetype = "COG", overwrite = TRUE,
                     gdal = c("COMPRESS=DEFLATE", "NUM_THREADS=ALL_CPUS"))

  # Remove redundant sidecar (COG is self-describing)
  aux <- paste0(filepath, ".aux.json")
  if (file.exists(aux)) file.remove(aux)

  .pg_record_checksum(filepath, varname, save_to)

  # Defensive: checksum categorical .aux.xml if terra wrote one
  if (any(terra::is.factor(rast))) {
    aux_xml <- paste0(filepath, ".aux.xml")
    if (file.exists(aux_xml))
      .pg_record_checksum(aux_xml, file.path("cog", paste0(varname, ".tif.aux.xml")), save_to)
  }

  invisible(NULL)
}

# Internal helper: record an MD5 checksum entry in _checksums.csv
.pg_record_checksum <- function(filepath, label, base_path) {
  md5_val <- tools::md5sum(filepath)
  checksum_file <- file.path(base_path, "_checksums.csv")
  row <- data.frame(varname = label, filename = basename(filepath), md5 = md5_val,
                    recorded_at = as.character(Sys.time()), stringsAsFactors = FALSE)
  if (file.exists(checksum_file)) {
    existing <- utils::read.csv(checksum_file, stringsAsFactors = FALSE)
    existing <- existing[existing$varname != label, ]
    updated <- rbind(existing, row)
  } else {
    updated <- row
  }
  utils::write.csv(updated, checksum_file, row.names = FALSE)
  invisible(NULL)
}

# Internal: re-stamp pg_* GDAL metatags (and terra units) on an existing COG
# from the current pgvariables row, without recomputing the raster data.
# Use this after editing data_raw/variables.csv + regenerating pgvariables.rda
# to propagate display metadata (label, unit, transform, plot_type, colormap, …) into built COGs.
# @param varname Variable name; must exist in pgvariables and in the cog/ dir.
# @param save_to Dataset root (same convention as save_pgvariable).
# @return Path to the restamped COG, invisibly.
# @keywords internal
.pg_restamp_metatags <- function(varname, save_to = pgout_path()) {
  rlang::check_installed("terra", reason = "to restamp COG metatags")
  if (!varname %in% pgvariables$name) {
    stop("varname '", varname, "' not found in pgvariables.")
  }
  filepath <- file.path(save_to, "cog", paste0(varname, ".tif"))
  if (!file.exists(filepath)) {
    stop("COG not found at: ", filepath, "\n  Run calc_pg() first.")
  }

  r <- terra::rast(filepath)

  # Sync terra units: set if non-empty, clear otherwise
  meta <- pgvariables[pgvariables$name == varname, ]
  terra::units(r) <- if (!is.na(meta$unit) && nzchar(meta$unit)) meta$unit else ""

  stats <- .pg_variable_stats(r, plot_type = meta$plot_type)
  terra::metags(r) <- .pg_build_metatags(varname, stats = stats)

  # Write to a sibling temp file (same filesystem → rename is atomic), then
  # replace the original. terra cannot write a lazy raster back to its own path.
  tmp_path <- tempfile(tmpdir = dirname(filepath), fileext = ".tif")
  on.exit(if (file.exists(tmp_path)) file.remove(tmp_path), add = TRUE)
  terra::writeRaster(r, tmp_path, filetype = "COG", overwrite = TRUE,
                     gdal = c("COMPRESS=DEFLATE", "NUM_THREADS=ALL_CPUS"))
  file.rename(tmp_path, filepath)

  aux <- paste0(filepath, ".aux.json")
  if (file.exists(aux)) file.remove(aux)

  .pg_record_checksum(filepath, varname, save_to)

  invisible(filepath)
}

# Internal: memory-bounded hive-partitioned builder for time-varying data.
# Writes one parquet partition per temporal slice following Apache Hive nested layout:
# year=YYYY/ for yearly; year=YYYY/<unit>=VV/ for sub-yearly. Also writes a gzipped CSV
# bundle and a pg_config.json manifest. Checksums all outputs.
# @keywords internal
.pg_build_timevarying <- function(base_path, config, version = NULL, type = NULL, overwrite = FALSE) {
  rlang::check_installed("terra", reason = "to build PRIO-GRID data from individual variables")

  hive_dir <- file.path(base_path, "timevarying")
  if (dir.exists(hive_dir)) {
    if (!overwrite) {
      message("Hive dataset already exists at '", hive_dir, "'. Use overwrite = TRUE to rebuild.")
      return(invisible(hive_dir))
    }
    unlink(hive_dir, recursive = TRUE)
    stale_csv <- file.path(base_path, "pg_timevarying.csv.gz")
    if (file.exists(stale_csv)) file.remove(stale_csv)
  }

  unit     <- pg_temporal_unit(config)
  n_cells  <- length(create_pg_indices(config))
  tmp_dir  <- file.path(pg_rawfolder(), "tmp", basename(tempfile()))
  dir.create(tmp_dir, recursive = TRUE)
  on.exit(unlink(tmp_dir, recursive = TRUE), add = TRUE)

  # ----- Phase 1: per-variable long parquet (date-sorted) -----
  tv      <- dplyr::filter(pgvariables, !static)$name
  present <- tv[file.exists(file.path(base_path, "cog", paste0(tv, ".tif")))]
  if (length(present) == 0L)
    stop("No time-varying COGs found in ", file.path(base_path, "cog"))

  for (v in present) {
    r  <- terra::rast(file.path(base_path, "cog", paste0(v, ".tif")))
    dt <- rast_to_df(r, static = FALSE, varname = v, config = config)
    data.table::setorder(dt, measurement_date)
    arrow::write_parquet(dt, file.path(tmp_dir, paste0(v, ".parquet")),
                         chunk_size = n_cells)
    rm(r, dt); gc()
  }

  # ----- Phase 2: per-slice wide assembly → hive partition + CSV rows -----
  dates      <- pg_dates(config)
  tmp_csv    <- file.path(tmp_dir, "_all.csv")
  partitions <- character(0L)

  for (d in dates) {
    d <- as.Date(d, origin = "1970-01-01")
    parts <- list()
    for (v in present) {
      sub <- dplyr::collect(
               dplyr::select(
                 dplyr::filter(arrow::open_dataset(file.path(tmp_dir, paste0(v, ".parquet"))),
                               measurement_date == d),
                 pgid, dplyr::all_of(v)))
      if (nrow(sub) > 0L) parts[[v]] <- data.table::setDT(sub)
    }
    if (length(parts) == 0L) next

    slice <- Reduce(function(a, b) merge(a, b, by = "pgid", all = TRUE), parts)
    for (v in setdiff(present, names(slice))) slice[, (v) := NA_real_]
    slice[, measurement_date := d]
    data.table::setcolorder(slice, c("pgid", "measurement_date", present))

    # Nested Hive partition subpath: year=YYYY for yearly; year=YYYY/<unit>=VV for sub-yearly
    part_subpath <- switch(unit,
      year    = paste0("year=", lubridate::year(d)),
      quarter = file.path(paste0("year=", lubridate::year(d)),
                           paste0("quarter=", lubridate::quarter(d))),
      month   = file.path(paste0("year=", lubridate::year(d)),
                           paste0("month=", sprintf("%02d", lubridate::month(d)))),
      week    = file.path(paste0("year=", lubridate::isoyear(d)),
                           paste0("week=", sprintf("%02d", lubridate::isoweek(d)))))

    part_dir <- file.path(hive_dir, part_subpath)
    dir.create(part_dir, recursive = TRUE, showWarnings = FALSE)
    pf <- file.path(part_dir, "part-0.parquet")
    arrow::write_parquet(slice, pf)
    .pg_record_checksum(pf,
                        file.path("timevarying", part_subpath, "part-0.parquet"),
                        base_path)
    data.table::fwrite(slice, tmp_csv, append = length(partitions) > 0L)
    partitions <- c(partitions, part_subpath)
  }

  # ----- Phase 3: CSV bundle, manifest, cleanup -----
  csv_gz <- file.path(base_path, "pg_timevarying.csv.gz")
  R.utils::gzip(tmp_csv, destname = csv_gz, overwrite = TRUE, remove = TRUE)
  .pg_record_checksum(csv_gz, "pg_timevarying.csv.gz", base_path)

  static_path <- file.path(base_path, "pg_static.parquet")
  static_vars <- if (file.exists(static_path))
    setdiff(names(arrow::open_dataset(static_path)), "pgid")
  else character(0L)

  all_vars <- c(static_vars, present)
  variables_meta <- lapply(all_vars, function(vn) {
    row <- pgvariables[pgvariables$name == vn, ]
    if (nrow(row) == 0L) return(list(name = vn))
    base <- as.list(row[1L, c("name", "static", "source_ids", "label", "unit",
                              "transform", "plot_type")])
    tag_val <- function(tags, key) {
      v <- tags$value[tags$name == key]
      if (length(v) == 0L) NA else v[[1]]
    }
    cog <- file.path(base_path, "cog", paste0(vn, ".tif"))
    if (file.exists(cog)) {
      tags <- terra::metags(terra::rast(cog))
      base$colormap     <- tag_val(tags, "pg_colormap")
      base$value_min    <- suppressWarnings(as.numeric(tag_val(tags, "pg_value_min")))
      base$value_max    <- suppressWarnings(as.numeric(tag_val(tags, "pg_value_max")))
      base$value_mean   <- suppressWarnings(as.numeric(tag_val(tags, "pg_value_mean")))
      base$value_std    <- suppressWarnings(as.numeric(tag_val(tags, "pg_value_std")))
      base$nunique      <- suppressWarnings(as.integer(tag_val(tags, "pg_nunique")))
      base$class_values <- tag_val(tags, "pg_class_values")
    } else {
      base$colormap     <- if (!is.na(row$plot_type) && nzchar(row$plot_type)) .pg_colormap(row$plot_type) else NA
      base$value_min    <- NA
      base$value_max    <- NA
      base$value_mean   <- NA
      base$value_std    <- NA
      base$nunique      <- NA
      base$class_values <- NA
    }
    base
  })
  names(variables_meta) <- all_vars

  meta <- list(
    priogrid_version  = version %||% as.character(utils::packageVersion("priogrid")),
    type              = type %||% "custom",
    generated_at      = as.character(Sys.Date()),
    grid = list(
      nrow   = config$nrow,
      ncol   = config$ncol,
      crs    = config$crs,
      extent = list(
        xmin = unname(config$extent["xmin"]),
        xmax = unname(config$extent["xmax"]),
        ymin = unname(config$extent["ymin"]),
        ymax = unname(config$extent["ymax"]))),
    temporal = list(
      resolution    = config$temporal_resolution,
      partition_key = if (unit == "year") "year" else c("year", unit),
      start_date    = as.character(config$start_date),
      end_date      = as.character(config$end_date)),
    pgid_to_coordinates = list(
      description    = "pgid is 1-based; cell 1 is the south-west corner (xmin, ymin), increasing eastward then northward.",
      col_from_west  = "(pgid - 1) %% ncol",
      row_from_south = "(pgid - 1) %/% ncol",
      lon_center     = "xmin + (col_from_west + 0.5) * (xmax - xmin) / ncol",
      lat_center     = "ymin + (row_from_south + 0.5) * (ymax - ymin) / nrow"),
    dataset_root         = paste(version %||% as.character(utils::packageVersion("priogrid")),
                                 type %||% "custom", sep = "/"),
    layout = list(
      cog         = "cog/<varname>.tif",
      timevarying = "timevarying/<partition>/part-0.parquet",
      static      = "pg_static.parquet",
      csv         = list(timevarying = "pg_timevarying.csv.gz",
                         static      = "pg_static.csv.gz")),
    static_variables      = static_vars,
    timevarying_variables = present,
    variables             = variables_meta,
    partitions            = partitions)

  json_path <- file.path(base_path, "pg_config.json")
  jsonlite::write_json(meta, json_path, auto_unbox = TRUE, pretty = TRUE)
  .pg_record_checksum(json_path, "pg_config.json", base_path)

  return(invisible(hive_dir))
}

# Internal: verify MD5 checksums for hive partition files.
# Reads _checksums.csv from base_path and warns on mismatch for any
# entry whose varname starts with "timevarying/".
# @keywords internal
.pg_verify_hive <- function(base_path) {
  cs_file <- file.path(base_path, "_checksums.csv")
  if (!file.exists(cs_file)) return(invisible(NULL))
  cs_df <- utils::read.csv(cs_file, stringsAsFactors = FALSE)
  hive_rows <- cs_df[startsWith(cs_df$varname, "timevarying/"), ]
  for (i in seq_len(nrow(hive_rows))) {
    fpath <- file.path(base_path, hive_rows$varname[i])
    if (!file.exists(fpath)) {
      warning("Hive partition missing: ", hive_rows$varname[i], call. = FALSE)
      next
    }
    actual <- tools::md5sum(fpath)
    if (actual != hive_rows$md5[i])
      warning("Checksum mismatch for hive partition '", hive_rows$varname[i],
              "': the file may be corrupted.", call. = FALSE)
  }
  invisible(NULL)
}

# Internal: resolve a spatial extent to the set of pgids it covers, using the
# config's grid definition. `extent` is a length-4 numeric c(xmin, xmax, ymin, ymax)
# in lon/lat (EPSG:4326) — the same convention as config$extent. For non-4326 configs
# the extent is reprojected internally (consistent with prio_blank_grid). A terra
# SpatExtent is used as-is in the grid's native CRS. Returns integer(0) on no overlap.
# @keywords internal
.pg_extent_to_pgids <- function(extent, config) {
  rlang::check_installed("terra", reason = "to subset PRIO-GRID data by spatial extent")
  pg <- prio_blank_grid(config)
  if (inherits(extent, "SpatExtent")) {
    e <- extent
  } else {
    nums <- as.numeric(extent)
    e <- if (config$crs != "epsg:4326") {
      sf::st_transform(
        sf::st_bbox(c(xmin = nums[1], xmax = nums[2], ymin = nums[3], ymax = nums[4]), crs = 4326),
        crs = config$crs
      )
    } else {
      terra::ext(nums)
    }
  }
  cropped <- tryCatch(terra::crop(pg, e), error = function(err) NULL)
  if (is.null(cropped)) return(integer(0))
  vals <- terra::values(cropped)
  as.integer(sort(unique(vals[!is.na(vals)])))
}

# Internal: apply optional temporal / spatial / column subsetting to an opened
# arrow time-varying dataset, then collect to a data.table. `has_year` marks whether
# the source exposes the hive `year` partition column (TRUE hive, FALSE legacy monolith).
# @keywords internal
.pg_collect_timevarying <- function(ds, has_year, years = NULL, start_date = NULL,
                                    end_date = NULL, pgids = NULL, extent = NULL,
                                    variables = NULL, config = NULL) {
  if (!is.null(variables)) {
    bad <- setdiff(variables, names(ds))
    if (length(bad) > 0)
      stop("Unknown variable(s) requested: ", paste(bad, collapse = ", "), ".\n",
           "  Available: ",
           paste(setdiff(names(ds), c("pgid", "measurement_date", "year")), collapse = ", "),
           call. = FALSE)
  }

  if (!is.null(years)) {
    sel_years <- as.integer(years)
    ds <- if (has_year) dplyr::filter(ds, year %in% sel_years)
          else           dplyr::filter(ds, lubridate::year(measurement_date) %in% sel_years)
  }
  if (!is.null(start_date)) { start_dt <- as.Date(start_date); ds <- dplyr::filter(ds, measurement_date >= start_dt) }
  if (!is.null(end_date))   { end_dt   <- as.Date(end_date);   ds <- dplyr::filter(ds, measurement_date <= end_dt) }

  sel_pgids <- if (!is.null(pgids)) as.integer(pgids) else NULL
  if (!is.null(extent)) {
    if (is.null(config))
      stop("Spatial 'extent' subsetting requires a resolvable config (grid dimensions). ",
           "Use release/version mode or pass config=.", call. = FALSE)
    ext_pgids <- .pg_extent_to_pgids(extent, config)
    sel_pgids <- if (is.null(sel_pgids)) ext_pgids else sort(unique(c(sel_pgids, ext_pgids)))
  }
  if (!is.null(sel_pgids)) ds <- dplyr::filter(ds, pgid %in% sel_pgids)

  if (!is.null(variables)) {
    keep <- c("pgid", "measurement_date", variables, if (has_year) "year")
    ds <- dplyr::select(ds, dplyr::any_of(keep))
  }

  data.table::setDT(dplyr::collect(ds))
}


# Internal admin helper: bulk-bootstrap _checksums.csv for all .tif/.parquet
# files in a resolved output folder. Useful after files have been placed without
# going through save_pgvariable() / read_pg_static() / read_pg_timevarying().
#
# @param config,version,type,spatial_hash,temporal_hash Passed to resolve_pg_mode().
# @param overwrite_existing Logical. If FALSE (default), skips files that already
#   have an entry in _checksums.csv. If TRUE, recomputes all entries.
# @return A list with elements `n_added` and `n_updated` (integers), invisibly.
# @keywords internal
.pg_bootstrap_checksums <- function(config = NULL,
                                    version = NULL,
                                    type = "05deg_yearly",
                                    spatial_hash = NULL,
                                    temporal_hash = NULL,
                                    overwrite_existing = FALSE) {

  cfg <- resolve_pg_mode(config, version, type, spatial_hash, temporal_hash)
  base_path <- cfg$base_path

  if (!dir.exists(base_path)) {
    stop("Output directory does not exist: ", base_path, call. = FALSE)
  }

  # Root-level parquet files (label = filename, e.g. "pg_static.parquet")
  parquet_files <- list.files(base_path, pattern = "\\.parquet$", full.names = FALSE)
  parquet_entries <- if (length(parquet_files) > 0L)
    data.frame(fname = parquet_files,
               label = parquet_files,
               stringsAsFactors = FALSE)
  else
    data.frame(fname = character(0), label = character(0), stringsAsFactors = FALSE)

  # COG .tif files under cog/ (label = varname without extension)
  cog_dir <- file.path(base_path, "cog")
  cog_files <- if (dir.exists(cog_dir))
    list.files(cog_dir, pattern = "\\.tif$", full.names = FALSE)
  else
    character(0)
  cog_entries <- if (length(cog_files) > 0L)
    data.frame(fname = file.path("cog", cog_files),
               label = tools::file_path_sans_ext(cog_files),
               stringsAsFactors = FALSE)
  else
    data.frame(fname = character(0), label = character(0), stringsAsFactors = FALSE)

  entries <- rbind(parquet_entries, cog_entries)

  if (nrow(entries) == 0L) {
    message("No .tif or .parquet files found in: ", base_path)
    return(invisible(list(n_added = 0L, n_updated = 0L)))
  }

  checksum_file <- file.path(base_path, "_checksums.csv")
  existing_labels <- if (file.exists(checksum_file)) {
    utils::read.csv(checksum_file, stringsAsFactors = FALSE)$varname
  } else {
    character(0)
  }

  n_added   <- 0L
  n_updated <- 0L

  for (i in seq_len(nrow(entries))) {
    fname <- entries$fname[i]
    label <- entries$label[i]
    already_exists <- label %in% existing_labels

    if (already_exists && !overwrite_existing) next

    .pg_record_checksum(file.path(base_path, fname), label, base_path)

    if (already_exists) {
      n_updated <- n_updated + 1L
    } else {
      n_added <- n_added + 1L
      existing_labels <- c(existing_labels, label)
    }
  }

  message(
    "Bootstrap complete for: ", base_path, "\n",
    "  Added:   ", n_added, " new checksum(s)\n",
    "  Updated: ", n_updated, " existing checksum(s)\n",
    "  Skipped: ", nrow(entries) - n_added - n_updated,
    " already-present checksum(s) (use overwrite_existing=TRUE to force)"
  )

  invisible(list(n_added = n_added, n_updated = n_updated))
}


#' Load a PRIO-GRID variable
#'
#' Loads a PRIO-GRID variable from disk and returns it as a lazy, file-backed
#' terra SpatRaster (no data is loaded into memory until the raster is explicitly
#' materialized). Supports optional lazy subsetting by layers and spatial windowing,
#' enabling a larger-than-memory workflow.
#'
#' Mode is determined by the \code{config} argument:
#' \itemize{
#'   \item \code{config = NULL} (default): loads from the official release (downloads if needed).
#'   \item \code{config = pg_config(...)}: loads from custom data built with that config.
#'   \item \code{spatial_hash} + \code{temporal_hash}: loads from a specific custom folder by hash.
#' }
#'
#' @param varname Character string with the variable name.
#' @param config A \code{pg_config} object for custom data, or NULL (default) for the
#'   official release.
#' @param version Character string specifying PRIOGRID version (e.g., "3.0.1").
#'   Only used in release mode (config = NULL). Defaults to current package version.
#' @param type Character string specifying release type (e.g., "05deg_yearly").
#'   Only used in release mode. Default: "05deg_yearly".
#' @param spatial_hash Character string with 6-character spatial hash. Requires
#'   temporal_hash. Loads from the specified custom folder directly.
#' @param temporal_hash Character string with 6-character temporal hash. Requires
#'   spatial_hash.
#' @param verify_checksums Logical. If TRUE, verifies the file's MD5 checksum
#'   against stored values. Default FALSE.
#' @param extent Optional spatial window. Either a \code{SpatExtent} (used as-is in
#'   the raster's CRS) or a length-4 numeric vector \code{c(xmin, xmax, ymin, ymax)}
#'   in EPSG:4326. Applied lazily via \code{terra::window()} — no data is loaded
#'   until the raster is materialized. Enables efficient reading of spatial subsets
#'   from large COGs (larger-than-memory workflow).
#' @param layers Optional layer selector. A character vector of layer names or an
#'   integer vector of layer indices. Applied lazily via \code{terra::subset()}.
#'
#' @return A lazy, file-backed \code{SpatRaster}. Data is not loaded into memory
#'   until explicitly materialized (e.g., via \code{terra::values()} or
#'   \code{terra::crop()}).
#' @export
#'
#' @examples
#' \dontrun{
#'   # Load from current official release (default)
#'   r <- load_pgvariable("cshapes_gwcode")
#'
#'   # Load from specific official release
#'   r <- load_pgvariable("cshapes_gwcode", version = "3.0.1")
#'
#'   # Load from custom data
#'   cfg <- pg_config(nrow = 180, ncol = 360)
#'   r <- load_pgvariable("cshapes_gwcode", config = cfg)
#'
#'   # Load from specific custom folder by hash
#'   r <- load_pgvariable("cshapes_gwcode",
#'                        spatial_hash = "ecf4dd",
#'                        temporal_hash = "727cca")
#'
#'   # Windowed / lazy load (larger-than-memory)
#'   r <- load_pgvariable("cru_tmp", extent = c(-30, 60, 35, 72), layers = 1:12)
#'   terra::inMemory(r)  # FALSE
#' }
load_pgvariable <- function(varname,
                            config = NULL,
                            version = NULL,
                            type = "05deg_yearly",
                            spatial_hash = NULL,
                            temporal_hash = NULL,
                            verify_checksums = FALSE,
                            extent = NULL,
                            layers = NULL) {
  rlang::check_installed("terra", reason = "to load PRIO-GRID variable rasters")

  has_hashes   <- !is.null(spatial_hash) && !is.null(temporal_hash)
  has_one_hash <- xor(!is.null(spatial_hash), !is.null(temporal_hash))

  if (has_one_hash) {
    stop("Both spatial_hash and temporal_hash must be provided together")
  }
  if (!is.null(config) && !is.null(version)) {
    stop("Cannot mix config with version parameter. Use config for custom mode or version for release mode.")
  }
  if (has_hashes && !is.null(version)) {
    stop("Cannot mix release parameters (version) with custom parameters (spatial_hash/temporal_hash)")
  }

  if (has_hashes) {
    base_dir <- pgout_path(spatial_hash = spatial_hash, temporal_hash = temporal_hash)
  } else if (!is.null(config)) {
    if (isTRUE(config$verbose)) {
      message("Loading custom data for config (", get_spatial_hash(config), "/", get_temporal_hash(config), ")")
    }
    base_dir <- pgout_path(spatial_hash = get_spatial_hash(config), temporal_hash = get_temporal_hash(config))
  } else {
    resolved_version <- version %||% as.character(packageVersion("priogrid"))
    download_priogrid(version = resolved_version, type = type)
    base_dir <- pgout_path(version = resolved_version, type = type)
  }

  filepath <- file.path(base_dir, "cog", paste0(varname, ".tif"))

  if (!file.exists(filepath)) {
    stop("Variable '", varname, "' not found at: ", filepath)
  }

  if (isTRUE(verify_checksums)) {
    cs_file <- file.path(base_dir, "_checksums.csv")
    if (file.exists(cs_file)) {
      cs_df <- utils::read.csv(cs_file, stringsAsFactors = FALSE)
      expected <- cs_df[cs_df$varname == varname, ]
      if (nrow(expected) == 1) {
        actual <- tools::md5sum(filepath)
        if (actual != expected$md5) {
          warning(
            "Checksum mismatch for '", varname, "': the file may be corrupted.\n",
            "  Expected MD5: ", expected$md5, "\n",
            "  Actual MD5:   ", actual, "\n",
            "  File: ", filepath, "\n",
            "  Recalculate with: calc_pg('", varname, "', overwrite = TRUE)",
            call. = FALSE)
        }
      }
    }
  }

  r <- terra::rast(filepath)

  # time() fallback for hand-placed COGs whose layer names are ISO dates
  # (save_pgvariable already stamps time(); this covers external files)
  static_flag <- pgvariables$static[pgvariables$name == varname]
  if (length(static_flag) == 1L && !isTRUE(static_flag) && all(is.na(terra::time(r)))) {
    parsed <- tryCatch(as.Date(names(r)), error = function(e) NULL)
    if (!is.null(parsed) && !any(is.na(parsed)))
      terra::time(r) <- parsed
  }

  # Lazy layer subsetting
  if (!is.null(layers)) {
    if (is.character(layers)) {
      bad <- setdiff(layers, names(r))
      if (length(bad) > 0L)
        stop("Layer name(s) not found in '", varname, "': ", paste(bad, collapse = ", "))
    } else {
      if (any(layers < 1L | layers > terra::nlyr(r)))
        stop("Layer index out of range for '", varname, "' (1:", terra::nlyr(r), ")")
    }
    r <- terra::subset(r, layers)
  }

  # Lazy spatial windowing
  if (!is.null(extent)) {
    if (inherits(extent, "SpatExtent")) {
      e <- extent
    } else {
      nums <- as.numeric(extent)
      e <- if (!terra::is.lonlat(r)) {
        rlang::check_installed("sf", reason = "to reproject spatial extent for non-4326 rasters")
        bbox <- sf::st_bbox(c(xmin = nums[1], xmax = nums[2],
                               ymin = nums[3], ymax = nums[4]), crs = 4326)
        bbox_t <- as.numeric(sf::st_transform(bbox, crs = terra::crs(r)))
        terra::ext(bbox_t[1], bbox_t[3], bbox_t[2], bbox_t[4])
      } else {
        terra::ext(nums)
      }
    }
    terra::window(r) <- e
  }

  r
}

#' Resolve PRIO-GRID data mode and paths
#'
#' Determines whether to use release or custom mode based on provided parameters,
#' and returns resolved settings. Does not perform any file operations or downloads.
#'
#' Mode is signalled by `config`:
#' - `config = NULL` (default) → release mode
#' - `config = pg_config(...)` → custom mode
#' - `spatial_hash` + `temporal_hash` → custom mode (explicit path override)
#'
#' @param config A `pg_config` object for custom mode, or NULL for release mode.
#' @param version Character string specifying PRIOGRID version (release mode only).
#' @param type Character string specifying release type (release mode only).
#' @param spatial_hash Character string with 6-character spatial hash (custom mode).
#' @param temporal_hash Character string with 6-character temporal hash (custom mode).
#' @param overwrite Logical. Whether to overwrite existing files.
#'
#' @return A list with:
#'   \item{mode}{"release" or "custom"}
#'   \item{base_path}{Resolved file path}
#'   \item{version}{Resolved version (NULL if custom)}
#'   \item{type}{Resolved type (NULL if custom)}
#'   \item{spatial_hash}{Resolved spatial hash (NULL if release)}
#'   \item{temporal_hash}{Resolved temporal hash (NULL if release)}
#'   \item{overwrite}{Possibly modified overwrite flag}
#'   \item{warning}{Warning message if any, otherwise NULL}
#'   \item{config}{Resolved config for data construction}
#'
#' @keywords internal
resolve_pg_mode <- function(config = NULL,
                            version = NULL,
                            type = "05deg_yearly",
                            spatial_hash = NULL,
                            temporal_hash = NULL,
                            overwrite = FALSE) {

  has_hashes <- !is.null(spatial_hash) && !is.null(temporal_hash)
  has_one_hash <- xor(!is.null(spatial_hash), !is.null(temporal_hash))
  has_config <- !is.null(config)
  has_version <- !is.null(version)

  if (has_one_hash) {
    stop("Both spatial_hash and temporal_hash must be provided together")
  }
  if (has_config && has_version) {
    stop("Cannot mix config with version parameter. Use config for custom mode or version for release mode.")
  }
  if (has_hashes && has_version) {
    stop("Cannot mix release parameters (version) with custom parameters (spatial_hash/temporal_hash)")
  }

  result <- list(
    mode = NULL,
    base_path = NULL,
    version = NULL,
    type = NULL,
    spatial_hash = NULL,
    temporal_hash = NULL,
    overwrite = overwrite,
    warning = NULL,
    config = NULL
  )

  if (has_hashes) {
    # Custom mode: explicit hashes override path, config used for data construction
    result$mode <- "custom"
    result$spatial_hash <- spatial_hash
    result$temporal_hash <- temporal_hash
    result$base_path <- pgout_path(spatial_hash = spatial_hash, temporal_hash = temporal_hash)
    result$config <- config

  } else if (has_config) {
    # Custom mode: config-driven
    result$mode <- "custom"
    result$spatial_hash <- get_spatial_hash(config)
    result$temporal_hash <- get_temporal_hash(config)
    result$base_path <- pgout_path(spatial_hash = result$spatial_hash, temporal_hash = result$temporal_hash)
    result$config <- config

  } else {
    # Release mode
    result$mode <- "release"
    result$version <- version %||% as.character(packageVersion("priogrid"))
    result$type <- type
    result$base_path <- pgout_path(version = result$version, type = result$type)
    result$config <- pg_release_config(result$version, result$type)

    if (overwrite) {
      result$warning <- paste0(
        "overwrite = TRUE is ignored for official releases. ",
        "Use build_release() to create releases."
      )
      result$overwrite <- FALSE
    }
  }

  result
}

#' Collect static (non-time-varying) PRIO-GRID data
#'
#' Loads all static variables and returns them either as a data.table or as
#' a list of rasters. See [pgvariables] for available variables.
#'
#' The mode is determined by the `config` argument:
#' - `config = NULL` (default): loads from the official release (downloads if needed).
#' - `config = pg_config(...)`: loads from custom data built with that config.
#'
#' @param config A `pg_config` object for custom data, or NULL (default) for the
#'   official release.
#' @param version Character string specifying PRIOGRID version (release mode only).
#' @param type Character string specifying release type. Default: "05deg_yearly".
#' @param spatial_hash Character string with 6-character spatial hash (custom only).
#' @param temporal_hash Character string with 6-character temporal hash (custom only).
#' @param as_raster Logical. If TRUE, returns list of SpatRasters. If FALSE
#'   (default), returns data.table.
#' @param test Logical. If TRUE, prints coverage summary for each variable.
#' @param overwrite Logical. If FALSE (default) and cached file exists, returns
#'   cached data. If TRUE, rebuilds from individual variables.
#' @param verify_checksums Logical. If TRUE, verifies checksums of cached files
#'   against stored MD5 values. Default FALSE.
#'
#' @return data.table with pgid as rows and variables as columns, or list of
#'   terra SpatRasters if as_raster=TRUE
#' @export
#'
#' @examples
#' \dontrun{
#'   # Load official release as data.table
#'   pg_dt <- read_pg_static()
#'
#'   # Load specific official release
#'   pg_dt <- read_pg_static(version = "3.0.1")
#'
#'   # Load custom data
#'   cfg <- pg_config(nrow = 180, ncol = 360)
#'   pg_dt <- read_pg_static(config = cfg)
#'
#'   # Load as rasters
#'   pg_rast <- read_pg_static(as_raster = TRUE)
#' }
read_pg_static <- function(config = NULL,
                           version = NULL,
                           type = "05deg_yearly",
                           spatial_hash = NULL,
                           temporal_hash = NULL,
                           as_raster = FALSE,
                           test = FALSE,
                           overwrite = FALSE,
                           verify_checksums = FALSE) {

  cfg <- resolve_pg_mode(config, version, type, spatial_hash, temporal_hash, overwrite)

  if (!is.null(cfg$warning)) {
    warning(cfg$warning)
  }

  if (cfg$mode == "release") {
    download_priogrid(version = cfg$version, type = cfg$type)
  }

  fname <- file.path(cfg$base_path, "pg_static.parquet")

  # Return cached if available (lightweight path — no terra needed)
  if (!as_raster && !test && file.exists(fname) && !cfg$overwrite) {
    if (isTRUE(verify_checksums)) {
      cs_file <- file.path(cfg$base_path, "_checksums.csv")
      if (file.exists(cs_file)) {
        cs_df <- utils::read.csv(cs_file, stringsAsFactors = FALSE)
        expected <- cs_df[cs_df$varname == "pg_static.parquet", ]
        if (nrow(expected) == 1) {
          actual <- tools::md5sum(fname)
          if (actual != expected$md5) {
            warning(
              "Checksum mismatch for cached 'pg_static.parquet': the file may be corrupted.\n",
              "  Expected MD5: ", expected$md5, "\n",
              "  Actual MD5:   ", actual, "\n",
              "  Rebuild with: read_pg_static(overwrite = TRUE)",
              call. = FALSE)
          }
        }
      }
    }
    return(arrow::read_parquet(fname))
  }

  # From here on, terra is required
  rlang::check_installed("terra", reason = "to build PRIO-GRID data from individual variables")

  # Load individual variables
  static <- pgvariables |> dplyr::filter(static)

  if (cfg$mode == "release") {
    rasters <- lapply(static$name, load_pgvariable,
                      version = cfg$version, type = cfg$type)
  } else {
    if (is.null(cfg$config)) {
      stop("config is required when using explicit spatial_hash/temporal_hash with read_pg_static()")
    }
    rasters <- lapply(static$name, load_pgvariable,
                      spatial_hash = cfg$spatial_hash,
                      temporal_hash = cfg$temporal_hash)
  }

  names(rasters) <- static$name
  rasters <- rasters[!is.na(rasters)]

  # data_config is the resolved config (release params or user config)
  data_config <- cfg$config

  # Test coverage if requested
  if (test) {
    pg_idx <- length(create_pg_indices(data_config))
    coverage_test <- dplyr::bind_rows(
      lapply(rasters, function(x) terra::freq(is.na(x))),
      .id = "variable"
    ) |>
      dplyr::filter(value == 0) |> # non-missing
      dplyr::mutate(coverage_pct = round(count / pg_idx, 4)) |>
      dplyr::select(variable, coverage_n = count, coverage_pct)
    message("# ---- Testing variable coverage ---- #")
    message(paste(capture.output(print(coverage_test, nrows = 50)), collapse = "\n"))
  }

  # Return rasters if requested
  if (as_raster) {
    return(rasters)
  }

  # Build data.table
  df <- rast_to_df(terra::rast(rasters), static = TRUE, config = data_config)

  # Save to cache
  arrow::write_parquet(df, fname)
  .pg_record_checksum(fname, "pg_static.parquet", cfg$base_path)
  static_csv <- file.path(cfg$base_path, "pg_static.csv.gz")
  data.table::fwrite(df, static_csv, compress = "gzip")
  .pg_record_checksum(static_csv, "pg_static.csv.gz", cfg$base_path)

  return(df)
}


#' Collect time-varying (non-static) PRIO-GRID data
#'
#' Loads all time-varying variables and returns them either as a data.table or as
#' a list of rasters. See [pgvariables] for available variables.
#'
#' The mode is determined by the `config` argument:
#' - `config = NULL` (default): loads from the official release (downloads if needed).
#' - `config = pg_config(...)`: loads from custom data built with that config.
#'
#' @param config A `pg_config` object for custom data, or NULL (default) for the
#'   official release.
#' @param version Character string specifying PRIOGRID version (release mode only).
#' @param type Character string specifying release type. Default: "05deg_yearly".
#' @param spatial_hash Character string with 6-character spatial hash (custom only).
#' @param temporal_hash Character string with 6-character temporal hash (custom only).
#' @param years Integer vector of years to keep. NULL (default) keeps all. Prunes hive
#'   partitions on the `year` column.
#' @param start_date,end_date Date (or Date-coercible) bounds on `measurement_date`
#'   (inclusive). NULL (default) leaves the respective bound open.
#' @param pgids Integer vector of PRIO-GRID cell ids to keep. NULL (default) keeps all cells.
#' @param extent Numeric `c(xmin, xmax, ymin, ymax)` in lon/lat (EPSG:4326), or a terra
#'   `SpatExtent` in the grid's native CRS; resolved to the pgids it covers and unioned
#'   with `pgids`. For non-4326 configs the lon/lat box is reprojected automatically.
#'   Requires `terra`. NULL (default) applies no spatial filter.
#' @param variables Character vector of time-varying variable columns to return (in addition
#'   to `pgid`, `measurement_date`, `year`). NULL (default) returns all variables.
#' @param as_raster Logical. If TRUE, returns list of SpatRasters. If FALSE
#'   (default), returns data.table.
#' @param test Logical. If TRUE, returns coverage summary data.frame.
#' @param overwrite Logical. If FALSE (default) and cached file exists, returns
#'   cached data. If TRUE, rebuilds from individual variables.
#' @param verify_checksums Logical. If TRUE, verifies checksums of cached files
#'   against stored MD5 values. Default FALSE.
#'
#' @return data.table with pgid + measurement_date as rows and variables as columns,
#'   or list of terra SpatRasters if as_raster=TRUE, or coverage test data.frame if test=TRUE
#' @export
#'
#' @examples
#' \dontrun{
#'   # Load official release as data.table
#'   pg_dt <- read_pg_timevarying()
#'
#'   # Load specific official release
#'   pg_dt <- read_pg_timevarying(version = "3.0.1")
#'
#'   # Load custom data
#'   cfg <- pg_config(nrow = 180, ncol = 360)
#'   pg_dt <- read_pg_timevarying(config = cfg)
#'
#'   # Subset: two years, a bounding box, and one variable
#'   pg_dt <- read_pg_timevarying(version = "3.0.1", years = c(2010, 2011),
#'                                extent = c(10, 12, 50, 52), variables = "cru_tmp")
#' }
read_pg_timevarying <- function(config = NULL,
                                version = NULL,
                                type = "05deg_yearly",
                                spatial_hash = NULL,
                                temporal_hash = NULL,
                                years = NULL,
                                start_date = NULL,
                                end_date = NULL,
                                pgids = NULL,
                                extent = NULL,
                                variables = NULL,
                                as_raster = FALSE,
                                test = FALSE,
                                overwrite = FALSE,
                                verify_checksums = FALSE) {

  cfg <- resolve_pg_mode(config, version, type, spatial_hash, temporal_hash, overwrite)
  if (!is.null(cfg$warning)) warning(cfg$warning)
  if (cfg$mode == "release") download_priogrid(version = cfg$version, type = cfg$type)

  subset_used <- !is.null(years) || !is.null(start_date) || !is.null(end_date) ||
                 !is.null(pgids) || !is.null(extent) || !is.null(variables)
  if (subset_used && (as_raster || test))
    stop("Subsetting arguments (years/start_date/end_date/pgids/extent/variables) are only ",
         "supported for the default data.table read, not with as_raster=TRUE or test=TRUE.",
         call. = FALSE)

  hive_dir <- file.path(cfg$base_path, "timevarying")
  legacy   <- file.path(cfg$base_path, "pg_timevarying.parquet")

  if (!as_raster && !test && !cfg$overwrite && (dir.exists(hive_dir) || file.exists(legacy))) {
    if (dir.exists(hive_dir)) {
      if (isTRUE(verify_checksums)) .pg_verify_hive(cfg$base_path)
      return(.pg_collect_timevarying(arrow::open_dataset(hive_dir), has_year = TRUE,
        years = years, start_date = start_date, end_date = end_date,
        pgids = pgids, extent = extent, variables = variables, config = cfg$config))
    }
    if (isTRUE(verify_checksums)) {
      cs_file <- file.path(cfg$base_path, "_checksums.csv")
      if (file.exists(cs_file)) {
        cs_df    <- utils::read.csv(cs_file, stringsAsFactors = FALSE)
        expected <- cs_df[cs_df$varname == "pg_timevarying.parquet", ]
        if (nrow(expected) == 1 && tools::md5sum(legacy) != expected$md5)
          warning("Checksum mismatch for cached 'pg_timevarying.parquet': the file may be corrupted.",
                  call. = FALSE)
      }
    }
    return(.pg_collect_timevarying(arrow::open_dataset(legacy), has_year = FALSE,
      years = years, start_date = start_date, end_date = end_date,
      pgids = pgids, extent = extent, variables = variables, config = cfg$config))
  }

  rlang::check_installed("terra", reason = "to build PRIO-GRID data from individual variables")
  timevarying <- pgvariables |> dplyr::filter(!static)
  data_config <- cfg$config

  if (test || as_raster) {
    if (cfg$mode == "release") {
      rasters <- lapply(timevarying$name, load_pgvariable,
                        version = cfg$version, type = cfg$type)
    } else {
      if (is.null(cfg$config))
        stop("config is required when using explicit spatial_hash/temporal_hash with read_pg_timevarying()")
      rasters <- lapply(timevarying$name, load_pgvariable,
                        spatial_hash = cfg$spatial_hash, temporal_hash = cfg$temporal_hash)
    }
    names(rasters) <- timevarying$name
    rasters <- rasters[!is.na(rasters)]

    if (test) {
      pg_idx <- length(create_pg_indices(data_config))
      coverage_test <- dplyr::bind_rows(
        lapply(rasters, function(x) terra::freq(is.na(x))),
        .id = "variable"
      ) |>
        dplyr::filter(value == 0) |>
        dplyr::mutate(
          coverage_pct     = round(count / pg_idx, 4),
          measurement_date = lapply(rasters, names) |> unlist()
        ) |>
        dplyr::select(variable, measurement_date, coverage_n = count, coverage_pct)
      return(coverage_test)
    }
    return(rasters)
  }

  .pg_build_timevarying(base_path = cfg$base_path, config = data_config,
                        version = cfg$version, type = cfg$type, overwrite = TRUE)
  .pg_collect_timevarying(arrow::open_dataset(hive_dir), has_year = TRUE,
    years = years, start_date = start_date, end_date = end_date,
    pgids = pgids, extent = extent, variables = variables, config = data_config)
}

#' Build a PRIO-GRID hive-partitioned dataset
#'
#' Memory-safe alternative to `read_pg_timevarying()` that writes the hive
#' partitioned parquet dataset and CSV bundle without loading the full table.
#' Useful for manual rebuild and re-upload workflows.
#'
#' @param config A `pg_config` object for custom data, or NULL (default) for the
#'   official release.
#' @param version Character string specifying PRIOGRID version (release mode only).
#' @param type Character string specifying release type. Default: "05deg_yearly".
#' @param spatial_hash 6-character MD5 hash of spatial options (advanced use).
#' @param temporal_hash 6-character MD5 hash of temporal options (advanced use).
#' @param overwrite Logical. If TRUE, rebuilds even if output already exists.
#'
#' @return Invisibly returns the base output path.
#' @export
build_pg_dataset <- function(config = NULL, version = NULL, type = "05deg_yearly",
                             spatial_hash = NULL, temporal_hash = NULL,
                             overwrite = FALSE) {
  cfg <- resolve_pg_mode(config, version, type, spatial_hash, temporal_hash)
  .pg_build_timevarying(base_path = cfg$base_path, config = cfg$config,
                        version = cfg$version, type = cfg$type, overwrite = overwrite)
  invisible(cfg$base_path)
}

#' Build an official PRIO-GRID release
#'
#' Sets config to specified configuration, calculates all variables to custom
#' location, then copies them to the official release folder. This ensures
#' consistency between custom and release workflows.
#'
#' @param version Character string with release version (e.g., "3.0.1")
#' @param type Character string with release type (e.g., "05deg_yearly")
#' @param nrow Number of rows
#' @param ncol Number of columns
#' @param crs Coordinate reference system
#' @param extent Named vector with xmin, xmax, ymin, ymax
#' @param temporal_resolution Temporal resolution string
#' @param start_date Start date (Date object)
#' @param end_date End date (Date object)
#'
#' @return NULL (invisibly). Called for side effects (creating release).
#' @export
#'
#' @examples
#' \dontrun{
#'   build_release(
#'     version = "3.0.1",
#'     type = "05deg_yearly",
#'     nrow = 360,
#'     ncol = 720,
#'     crs = "epsg:4326",
#'     extent = c(xmin = -180, xmax = 180, ymin = -90, ymax = 90),
#'     temporal_resolution = "1 year",
#'     start_date = as.Date("1850-12-31"),
#'     end_date = as.Date("2025-08-26")
#'  )
#' }
build_release <- function(version, type,
                          nrow, ncol,
                          crs, extent,
                          temporal_resolution,
                          start_date, end_date) {

  # Construct config from explicit arguments
  config <- pg_config(
    nrow = nrow, ncol = ncol, crs = crs, extent = extent,
    temporal_resolution = temporal_resolution,
    start_date = start_date, end_date = end_date
  )

  # Calculate
  calc_pg(overwrite = TRUE, config = config)
  read_pg_static(config = config, overwrite = TRUE)
  .pg_build_timevarying(base_path = pgout_path(config = config), config = config,
                        version = version, type = type, overwrite = TRUE)

  # Promote to release
  from_path <- pgout_path(config = config)
  to_path <- pgout_path(version = version, type = type, config = config)

  dir.create(dirname(to_path), recursive = TRUE, showWarnings = FALSE)
  file.copy(from_path, dirname(to_path), recursive = TRUE)
  file.rename(file.path(dirname(to_path), basename(from_path)), to_path)

  current_wd <- getwd()
  setwd(file.path(pg_rawfolder(), "priogrid"))
  safe_version <- stringr::str_replace_all(version, "\\.", "_")
  rel_dir   <- file.path("releases", version, type)
  all_top   <- list.files(rel_dir, full.names = TRUE)
  csv_files <- list.files(rel_dir, pattern = "\\.csv\\.gz$", full.names = TRUE)
  base_zip  <- paste("priogrid", safe_version, type, sep = "_")
  zip(zipfile = paste0(base_zip, ".zip"),     files = setdiff(all_top, csv_files))
  zip(zipfile = paste0(base_zip, "_csv.zip"), files = csv_files)
  setwd(current_wd)

  message("Release built at: ", to_path)
  invisible(NULL)
}

#' List custom PRIO-GRID data folders
#'
#' Scans all custom data folders created by [calc_pg()] and prints a summary
#' of each configuration. Returns an indexed list of [pg_config()] objects
#' for direct programmatic use.
#'
#' @return An invisible named list of `pg_config` objects, one per custom folder.
#'   Configs are indexed by position; use `[[i]]` to select one.
#' @export
#'
#' @examples
#' \dontrun{
#'   customs <- pg_list_custom()
#'   # [1] abc123/xyz789: nrow=360, ncol=720, 1850-12-31 to 2025-08-26, 3 vars
#'
#'   read_pg_static(config = customs[[1]])
#'   calc_pg("new_var", config = customs[[2]])
#' }
pg_list_custom <- function() {
  base_path <- file.path(pg_rawfolder(), "priogrid", "custom")

  if (!dir.exists(base_path)) {
    message("No custom PRIOGRID data found.")
    return(invisible(list()))
  }

  config_files <- list.files(base_path, pattern = "^_config\\.R$",
                             recursive = TRUE, full.names = TRUE)

  if (length(config_files) == 0) {
    message("No custom PRIOGRID data found.")
    return(invisible(list()))
  }

  configs <- vector("list", length(config_files))

  for (i in seq_along(config_files)) {
    folder <- dirname(config_files[i])
    parts <- strsplit(folder, .Platform$file.sep)[[1]]
    t_hash <- parts[length(parts)]
    s_hash <- parts[length(parts) - 1]

    env <- new.env(parent = getNamespace("priogrid"))
    tryCatch(
      sys.source(config_files[i], envir = env),
      error = function(e) NULL
    )
    cfg <- env$cfg

    n_vars <- length(list.files(file.path(folder, "cog"), pattern = "\\.tif$"))
    created <- format(file.info(config_files[i])$mtime, "%Y-%m-%d")

    cat(sprintf("[%d] %s/%s: nrow=%d, ncol=%d, %s to %s, %d vars, created %s\n",
      i, s_hash, t_hash,
      cfg$nrow, cfg$ncol,
      format(cfg$start_date), format(cfg$end_date),
      n_vars, created
    ))

    configs[[i]] <- cfg
  }

  invisible(configs)
}

#' Download and initialize official PRIO-GRID release
#'
#' Downloads the official PRIO-GRID release data from the PRIO CDN and extracts
#' it to the local raw data folder. Only downloads if the file doesn't exist
#' or if overwrite=TRUE.
#'
#' @param version Character string with release version
#' @param type Character string with release type (default: "05deg_yearly")
#' @param overwrite Logical. If TRUE, re-downloads even if file exists.
#' @param list_releases Logical. If TRUE, prints and returns a data.frame of
#'   available releases instead of downloading. Default FALSE.
#'
#' @return NULL (invisibly). Called for side effects (downloading data).
#' @export
#'
#' @examples
#' \dontrun{
#'   # Download latest official release
#'   download_priogrid()
#'
#'   # Download specific release
#'   download_priogrid(version = "3.0.1", type = "05deg_yearly")
#'
#'   # List releases
#'   download_priogrid(list_releases = TRUE)
#' }
download_priogrid <- function(version = NULL,
                              type = "05deg_yearly",
                              overwrite = FALSE,
                              list_releases = FALSE) {

  if(is.null(version)){
    version <- packageVersion("priogrid")
  }

  releases <- list(
    "3.0.0_05deg_yearly" = "https://cdn.cloud.prio.org/files/379b7254-b47c-48f3-a650-783348d0ff7e",
    "3.0.1_05deg_yearly" = "https://cdn.cloud.prio.org/files/1c76a606-8efa-4dc0-a938-301c4e9331e6"
  )

  if(list_releases == TRUE){
   df <- stringr::str_split(names(releases), "_", n = 2, simplify = T) |> as.data.frame()
   df$url <- unlist(releases)
   names(df) <- c("version", "type", "url")
   df <- dplyr::tibble(df)
   return(print(df))
  }

  key <- paste(version, type, sep = "_")
  if (!key %in% names(releases)) {
    stop("Unknown release: ", version, " (", type, ")")
  }

  fname <- paste0("priogrid_", gsub("\\.", "_", version), "_", type, ".zip")
  fpath <- file.path(pg_rawfolder(), "priogrid", fname)

  if (!file.exists(fpath) || overwrite) {
    dir.create(dirname(fpath), recursive = TRUE, showWarnings = FALSE)
    report <- pg_download_batch(releases[[key]], fpath)
    if (!isTRUE(report$success)) {
      stop("Could not download PRIO-GRID ", version, " (", type, "): ",
           if (is.na(report$error)) paste("HTTP", report$status_code) else report$error,
           call. = FALSE)
    }
    if (file.exists(fpath)) unlink(fpath)
    file.rename(report$partfile, report$destfile)
  }

  suppressWarnings(
    unzip(fpath, exdir = file.path(pg_rawfolder(), "priogrid"), overwrite = overwrite)
  )

  invisible(NULL)
}
